# Generated by Django 3.0.6 on 2020-05-23 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=250)),
                ('goal_id', models.IntegerField(default=1)),
                ('created_by', models.CharField(max_length=250)),
                ('moved_by', models.CharField(max_length=250)),
                ('owner', models.CharField(max_length=250)),
                ('goal_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrumy_goal', to='ajayiezekiel9000scrumy.GoalStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_by', models.CharField(max_length=250)),
                ('created_by', models.CharField(max_length=250)),
                ('moved_from', models.CharField(max_length=250)),
                ('moved_to', models.CharField(max_length=250)),
                ('time_of_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumy_history', to='ajayiezekiel9000scrumy.ScrumyGoals')),
            ],
        ),
    ]
