# Generated by Django 3.0.6 on 2020-05-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajayiezekiel9000scrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalstatus',
            options={'verbose_name_plural': 'GoalStatus'},
        ),
        migrations.AlterModelOptions(
            name='scrumygoals',
            options={'verbose_name_plural': 'ScrumyGoals'},
        ),
        migrations.AlterModelOptions(
            name='scrumyhistory',
            options={'verbose_name_plural': 'ScrumyHistories'},
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='moved_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='owner',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='moved_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='moved_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='moved_to',
            field=models.CharField(max_length=50),
        ),
    ]
