# Generated by Django 3.0.6 on 2020-05-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajayiezekiel9000scrumy', '0002_auto_20200524_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
